file = open("mybucketlist.txt", "w")
file.write("1. Skydiving\n")
file.write("2. Visit Los Angeles\n")
file.write("3. Become master at coding\n")
file.close()
print("Bucket list has been created and saved to mybucketlist.txt")

file = open("mybucketlist.txt", "r")
content = file.read()
print("contents of my bucket list are:")
print(content)
file.close()

file = open("mybucketlist.txt", "r")
lines = file.readlines()
print("len of my bucket list is:", len(lines))
print(lines)
file.close()

file = open("mybucketlist.txt", "a")
file.write("4. become good at studying\n")
file.write("5. Travel to Japan\n")
file.close()
print("New items have been added to the bucket list.")

file = open("mybucketlist.txt", "r")
content = file.read()
print("contents of my bucket list are:")
print(content)
file.close()